apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3","meta.helm.sh/release-name":"dev","meta.helm.sh/release-namespace":"chatbot"},"creationTimestamp":"2025-05-24T08:36:28Z","generation":6,"labels":{"app.kubernetes.io/instance":"dev","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"chatbot","app.kubernetes.io/version":"0.2.0","helm.sh/chart":"chatbot-0.0.0"},"name":"dev-chatbot","namespace":"chatbot","resourceVersion":"55257439","uid":"ebb4dff8-f287-4b04-bbae-d2ae028aa3d4"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/instance":"dev","app.kubernetes.io/name":"chatbot","component":"service-pod"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"checksum/config":"aa450e5225767230e6fa36fa22d82befae9d4589af23883d1e69b4652dd5072a","checksum/volumes":"d22e6de14bed8af73325412fa8ba1f32cdab9b7c3d92f3e2fcaeb53237e4dae3","prometheus.io/path":"/hams/metrics","prometheus.io/port":"8079","prometheus.io/scrape":"true"},"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"dev","app.kubernetes.io/name":"chatbot","component":"service-pod"}},"spec":{"containers":[{"args":["start","--config","/opt/app/configs/config.yaml","--secrets","/opt/app/secrets"],"command":["sleep","infinity"],"image":"ghcr.io/polecatworks/chatbot-root:main","imagePullPolicy":"Always","lifecycle":{"preStop":{"httpGet":{"path":"/hams/stop","port":"http-health","scheme":"HTTP"}}},"livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/hams/alive","port":"http-health","scheme":"HTTP"},"initialDelaySeconds":30,"periodSeconds":30,"successThreshold":1,"timeoutSeconds":1},"name":"chatbot","ports":[{"containerPort":8079,"name":"http-health","protocol":"TCP"},{"containerPort":8080,"name":"http-web","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/hams/ready","port":"http-health","scheme":"HTTP"},"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"resources":{},"securityContext":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/opt/app/configs","name":"configs"},{"mountPath":"/opt/app/secrets","name":"secrets"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"dockerconfigjson-ghcr-io"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"dev-chatbot","serviceAccountName":"dev-chatbot","terminationGracePeriodSeconds":30,"volumes":[{"configMap":{"defaultMode":420,"name":"dev-chatbot"},"name":"configs"},{"name":"secrets","projected":{"defaultMode":420,"sources":[{"secret":{"items":[{"key":"app_password","path":"bot/app_password"},{"key":"app_id","path":"bot/app_id"}],"name":"dev-chatbot"}}]}}]}}},"status":{"conditions":[{"lastTransitionTime":"2025-05-24T09:02:47Z","lastUpdateTime":"2025-05-24T09:02:47Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"},{"lastTransitionTime":"2025-05-24T09:30:31Z","lastUpdateTime":"2025-05-24T09:30:31Z","message":"ReplicaSet \"dev-chatbot-5cb5c8bc47\" has timed out progressing.","reason":"ProgressDeadlineExceeded","status":"False","type":"Progressing"}],"observedGeneration":6,"replicas":2,"unavailableReplicas":2,"updatedReplicas":1}}
    meta.helm.sh/release-name: dev
    meta.helm.sh/release-namespace: chatbot
  creationTimestamp: "2025-05-24T08:36:28Z"
  generation: 7
  labels:
    app.kubernetes.io/instance: dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: chatbot
    app.kubernetes.io/version: 0.2.0
    helm.sh/chart: chatbot-0.0.0
  name: dev-chatbot
  namespace: chatbot
  resourceVersion: "55266999"
  uid: ebb4dff8-f287-4b04-bbae-d2ae028aa3d4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: dev
      app.kubernetes.io/name: chatbot
      component: service-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: aa450e5225767230e6fa36fa22d82befae9d4589af23883d1e69b4652dd5072a
        checksum/volumes: d22e6de14bed8af73325412fa8ba1f32cdab9b7c3d92f3e2fcaeb53237e4dae3
        prometheus.io/path: /hams/metrics
        prometheus.io/port: "8079"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dev
        app.kubernetes.io/name: chatbot
        component: service-pod
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: ghcr.io/polecatworks/chatbot-root:main
        imagePullPolicy: Always
        lifecycle:
          preStop:
            httpGet:
              path: /hams/stop
              port: http-health
              scheme: HTTP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /hams/alive
            port: http-health
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: chatbot
        ports:
        - containerPort: 8079
          name: http-health
          protocol: TCP
        - containerPort: 8080
          name: http-web
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /hams/ready
            port: http-health
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app/configs
          name: configs
        - mountPath: /opt/app/secrets
          name: secrets
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerconfigjson-ghcr-io
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: dev-chatbot
      serviceAccountName: dev-chatbot
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: dev-chatbot
        name: configs
      - name: secrets
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: app_password
                path: bot/app_password
              - key: app_id
                path: bot/app_id
              name: dev-chatbot
status:
  conditions:
  - lastTransitionTime: "2025-05-24T09:02:47Z"
    lastUpdateTime: "2025-05-24T09:02:47Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-05-24T10:07:51Z"
    lastUpdateTime: "2025-05-24T10:07:51Z"
    message: ReplicaSet "dev-chatbot-79d44775bc" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 7
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
