---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatbot.fullname" . }}
  labels:
    {{- include "chatbot.labels" . | nindent 4 }}
data:
  serviceconfig.yaml: |
    {{- include "chatbot.config" . | nindent 4 }}
