apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}
  labels:
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
{{ toYaml .Values.service.sessionAffinityConfig | indent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http-web
      protocol: TCP
      name: http-web
    - name: http-envoy-prom
      port: 15020
      protocol: TCP
      targetPort: 15020
  selector:
    component: service-pod
    {{- include "chatbot.selectorLabels" . | nindent 4 }}
