---
hams:
  address: 127.0.0.1:8079
  prefix: hams
  logging: true
  checks:
    timeout: 5
    fails: 2
    preflights: []
    # - http://localhost:4201
    shutdowns: []
runtime:
  stack_size: 3145728
  threads: 4
webservice:
  prefix: polecatteamsbot
  address: 0.0.0.0:8080
  forwarding_headers: []
persistence:
  db:
    pool_size: 20
    automigrate: true
    connection:
      url: postgres://localhost:5432/log4ham-pg-log4ham
      username_file: db/username
      password_file: db/password
teams:
  bot_endpoint: https://informally-large-terrier.ngrok-free.app/api/messages
  id_file: app/id
  secret_file: app/secret
  tenant_id: 1fd80b61-a805-4a57-879b-45ddb39a660d
  scopes:
    - api://87de8678-74cc-4a80-8987-ce00baf25087/.default
  auth_endpoint: https://login.microsoftonline.com/1fd80b61-a805-4a57-879b-45ddb39a660d/v2.0
  # /.well-known/openid-configuration
  auth_sleep: 30s
  auth_margin: 3580s
