---
hams:
  address: 127.0.0.1:8079
  prefix: hams
  logging: true
  checks:
    timeout: 5
    fails: 2
    preflights: []
    # - http://localhost:4201
    shutdowns: []
runtime:
  stack_size: 3145728
  threads: 4
webservice:
  prefix: polecatteamsbot
  address: 0.0.0.0:8080
  forwarding_headers: []
persistence:
  db:
    pool_size: 20
    automigrate: true
    connection:
      url: postgres://localhost:5432/log4ham-pg-log4ham
      username_file: db/username
      password_file: db/password
teams:
  auth: https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token
  id_file: app/id
  password_file: app/password
  openid: https://login.microsoftonline.com/1fd80b61-a805-4a57-879b-45ddb39a660d/v2.0/.well-known/openid-configuration
