---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chatbot-app
spec:
  releaseName: chatbot-app
  chart:
    spec:
      chart: helm-charts/chatbot
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: polecatworks
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/polecatworks/chatbot-root
      tag: main
      pullPolicy: Always
    imagePullSecrets:
    - name: dockerconfigjson-ghcr-io
    configs:
      logging:
        version: 1
        disable_existing_loggers: False
        formatters:
          standard:
            format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        handlers:
          console:
            class: logging.StreamHandler
            formatter: standard
            level: INFO
            stream: ext://sys.stdout
        loggers:
          chatbot.hams:
            handlers: [console]
            level: WARNING
            propagate: False
        root:
          handlers: [console]
          level: INFO
      webservice:
        url: http://0.0.0.0:8080
        prefix: pie/v0
      bot:
        app_id: "" # Disable bot authentication for dev
        app_password: "" # Disable bot authentication for dev
      aiclient:
        model: gemini-2.0-flash
        model_provider: google_genai
        # model_provider: github
        # github_model_repo: openai/gpt-4.1
        # github_api_base_url: https://models.github.ai/inference
        # model: model-name

        temperature: 1.0
        # max_tokens: 500
        context_length: 4096
        stop_sequences: []
        timeout: 60
      myai:
        system_instruction:
          - text: "You are a helpful assistant."
        toolbox:
          max_concurrent: 10
          tools:
          - name: sum_numbers
            max_instances: 10
          - name: multiply_numbers
            max_instances: 10
          - name: search_records_by_name
            max_instances: 10
          - name: delete_record_by_id
            max_instances: 10
          - name: get_weather
            max_instances: 10
          - name: get_time
            max_instances: 10
          - name: count_calls
            max_instances: 10
          mcps:
          - name: customers
            url: http://localhost:8100/mcp
            transport: sse

      hams:
        url: http://localhost:8079
        prefix: hams
        shutdownDuration: P0DT0H0M10S
        checks:
          timeout: 5
          fails: 2
          preflights: []
          shutdowns: []
            # - name: Sidecar shutdown
            #   http: http://localhost:15000/quitquitquit
            #   method: POST
            #   description: Quit the istio sidecar
            #   returncode: 200

          # - name: Istio
          #   http: http://google.com
          #   description: Check that Istio is up
          #   returncode: 300
          # - name: Istio
          #   http: http://google.co.uk
          #   description: Check that Istio is up
      events:
        chunkDuration: P0DT0H0M1S
        checkTime: P0DT0H0M0.500S
        maxChunks: 100
