name: Tag Docker Image on Release

on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io


  # IMAGE_NAME will be set in the job using github.repository
  # to ensure it's correctly formatted (lowercase)

jobs:
  tag_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # Required for cosign if we add signing later, good to have

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: imjasonh/setup-crane@v0.1

      - name: Login to GHCR
        run: |
          echo "${{ github.token }}" | crane auth login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Pull, Retag, and Push Docker Image
        run: |
          RELEASE_TAG=${{ github.event.release.tag_name }}
          # Ensure RELEASE_TAG is not empty
          if [ -z "$RELEASE_TAG" ]; then
            echo "Error: Release tag is empty. Skipping Docker tag and push."
            exit 1
          fi

          # The image should have been built and pushed by another workflow, tagged with the commit SHA
          # Let's assume the image name format from other workflows.
          # We need to ensure the IMAGE_NAME is correctly cased (lowercase for ghcr.io)

          IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

          SOURCE_SHA_TAG="sha-${{ github.sha }}"
          IMAGE_BASE="${{ env.REGISTRY }}/${IMAGE_NAME}"

          crane copy "${IMAGE_BASE}:${SOURCE_SHA_TAG}" "${IMAGE_BASE}:${RELEASE_TAG}"


      # - name: Update GitHub Release with Docker Image Info
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     RELEASE_TAG=${{ github.event.release.tag_name }}
      #     IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      #     IMAGE_URI="${{ env.REGISTRY }}/${IMAGE_NAME}:${RELEASE_TAG}"

      #     RELEASE_ID=$(gh api repos/${{ github.repository }}/releases/tags/${RELEASE_TAG} --jq '.id')
      #     BODY="Docker image available at \`${IMAGE_URI}\`"

      #     gh api \
      #   --method PATCH \
      #   -H "Accept: application/vnd.github+json" \
      #   /repos/${{ github.repository }}/releases/${RELEASE_ID} \
      #   -f body="$(gh api repos/${{ github.repository }}/releases/${RELEASE_ID} --jq '.body')\n\n${BODY}"
      #   shell: bash
